name: testing_dev
services:
  frontend:
    container_name: react
    build:
      context: ./reactapp
      dockerfile: Dockerfile.dev
    volumes:
      - ./reactapp:/usr/frontend
      - /usr/frontend/node_modules/
    ports:
      - "4000:3000"
    develop:
      watch: 
        - path: ./reactapp
          action: sync
          target: /usr/frontend
          ignore:
            - node_modules/

networks:
  default:
    name: testing_dev_network
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"


