services:
  frontend:
    build:
      context: ./reactapp
      dockerfile: Dockerfile.dev
    volumes:
      - ./reactapp:/usr/frontend
      - /usr/frontend/node_modules/
    ports:
      - "4000:3000"
    develop:
      watch: 
        - path: ./reactapp
          action: sync
          target: /usr/frontend
          ignore:
            - node_modules/
    
